# below task work on servers node
- name: Add multiple entries to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{pgbrepo_node_ip}} {{pgbrepo_node_name}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HOSTS"
    state: present

# Ensure datapath directory exists pgBackRest repository

- name: Ensure pgBackRest repository datapath directory exists
  ansible.builtin.file:
    path: "{{ pgbackRest_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: "0750"
    recurse: yes


- name: Create pgbackrest config for local storage
  template:
    src: pgbackrest_dbserver.yaml.j2
    dest: /etc/pgbackrest.conf

- name: Create pgbackrest config for local storage
  template:
    src: pgbackrest.service.j2
    dest: /etc/systemd/system/pgbackrest.service
    
- name: start pgbackrest server
  service: name=pgbackrest state=started enabled=true daemon_reload=true
  register: start_output