- name: Update /etc/hosts with inventory IPs and hostnames
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host]['ansible_host'] }} {{ hostvars[host]['inventory_hostname'] }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HOSTS"
    state: present


- name: install Percona-release package 
  tags: postgres,db,etcd,patroni
  command: percona-release setup ppg{{version}}
  # environment: "{{proxy_env}}"
  when: ansible_distribution == "Ubuntu" and percona_package_install

- name: Install percona-haproxy
  tags: postgres,db,etcd,patroni
  apt:
    name:
    - percona-haproxy
  # environment: "{{proxy_env}}"
  when: ansible_distribution == "Ubuntu" and percona_package_install



- name: Config HAProxy
  tags: haconf
  template:
    src: config.cfg.j2
    dest: /etc/haproxy/haproxy.cfg


- name: Wait for 3 seconds
  ansible.builtin.pause:
    seconds: 3



- name: start haproxy server
  service: name=haproxy state=restarted enabled=true
