
#configuration vars true or false
create_certs: true
base_package_install: true
percona_package_install: true
install_etcd: true
install_patroni: true
install_haservers: true
pgbouncer_install: true
set_hapgbouncer_port: true
enable_pgbackrest: true

#patroni,postgres,pgbackrest and haproxy vars
version: 17
etcd_data: /var/lib/etcd
cluster_token: PostgreSQL_HA_Cluster_1
cluster_state: new
data_dir: "/var/lib/postgresql/{{version}}/main"
pg_bin_dir: "/usr/lib/postgresql/{{version}}/bin"
ca_path: /etc/ssl/certs/pg_ha
log_directory: '/var/log/postgresql/'
log_filename: 'postgresql-%Y%m%d.log'
namespace: "percona_lab"
scope: "cluster_1"      # cluster name

#backup vars
backup_type: local    #local or s3
##############
compress_type: gz
#s3

s3_bucket: 
s3_endpoint: 
s3_key: 
s3_key_secret: 
s3_port: 
s3_region: local
verify_tls: n         # y or n
uri_style: path

#local

pgbackRest_dir: /var/lib/pgbackrest
##############

#postgres and pgbouncer users

postgres_pass: postgres_pass
repluser_pass: repluser_pass

pgbouncer_user: pgbouncer
pgbouncer_pass: pgbouncer_pass

#etcd, postgres,pgbouncer and ha proxy ports
postgres_port: 5432
pgbouncer_port: 6432
postgres_rest_port: 8008
primary_port: 5000
repl_port: 5001
stat_port: 7000
etcd_client_port: 2379
etcd_comm_port: 2380
#proxy
proxy_env:
  http_proxy: 
  https_proxy: 